INPUT:
  MIN_SIZE_TRAIN: (640, 768, 896)
  MAX_SIZE_TRAIN: 896
  ROTATION_RANGE: (20, 10)

MODEL:
  META_ARCHITECTURE: "ARPN"
  WEIGHT: "../hard_space/models/ICDAR13_15_17_Trial_AFPN_LERB_RT_Spotter_IC15_pretrained_RECG_REFINED_continue/model_1000000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 64
    FREEZE_CONV_BODY_AT: -1
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvARPNHead"

  RROI_BOX_HEAD:
    NUM_CLASSES: 2 # Text or non-Text
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    MLP_HEAD_DIM: 1024

  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)
    FG_IOU_THRESHOLD: 0.6
    BG_IOU_THRESHOLD: 0.6
    DETECTIONS_PER_IMG: 300
    NMS_TYPE: "remove"# "remove"
    NMS: 0.1

  REC_ON: False

  ROI_REC_HEAD:
    ALPHABET: "./data_cache/alphabet_seq.txt" #./data_cache/alphabet_docVQA_pro.txt ./data_cache/alphabet_IC13_IC15_IC17mlt_pro.txt
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    MAX_POSITIVE_NUM: 128
    REC_DETACH: False
    POOLER_RESOLUTION: (8, 35)
  RRPN:
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (2, 4, 8, 16, 32)
    GT_BOX_MARGIN: 1.4

  ARPN:
    BASE_SIZE: 640.
    SCALE_STACK: (0.25, 0.125, 0.0625, 0.03125, 0.015625)
    SIZE_STACK: (64, 128, 256, 512)
    NMS_TYPE: "remove"
    NMS_THRESH: 0.8
    SCORE_THRESH: 0.000

DATASETS:
  TRAIN: ("RRPN_E2E_LANGSEQ", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000)
  MAX_ITER: 240000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: '../hard_space/models/ICDAR13_15_17_Trial_AFPN_LERB_RT_Spotter_IC15_pretrained_RECG_REFINED_LANGSEQ_mlt_continue_detonly_MS_textness/'
