INPUT:
  MIN_SIZE_TRAIN: (640,)
  MAX_SIZE_TRAIN: 960
  ROTATION_RANGE: (20, 10)

MODEL:
  META_ARCHITECTURE: "ARPN"
  WEIGHT: "../hard_space/models/ICDAR13_15_17_Trial_AFPN_rEAST_ft_docVQA/model_0025000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvARPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"

  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)

  REC_ON: True

  ROI_REC_HEAD:
    ALPHABET: "./data_cache/alphabet_docVQA_pro.txt"
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    MAX_POSITIVE_NUM: 128
    REC_DETACH: False

  RRPN:
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (2, 4, 8, 16, 32)
    GT_BOX_MARGIN: 1.2

  ARPN:
    BASE_SIZE: 640.
    SCALE_STACK: (0.25, 0.125, 0.0625, 0.03125, 0.015625)
    SIZE_STACK: (32, 64, 128, 256)
    NMS_TYPE: "remove"
    NMS_THRESH: 0.7
    SCORE_THRESH: 0.000

DATASETS:
  TRAIN: ("RRPN_E2E", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 100000)
  MAX_ITER: 120000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: '../hard_space/models/ICDAR13_15_17_Trial_AFPN_E2E_rEAST_ft_docVQA_v2/'
