INPUT:
  MIN_SIZE_TRAIN: (640,)
  MAX_SIZE_TRAIN: 640
  ROTATION_RANGE: (20, 10)

MODEL:
  META_ARCHITECTURE: "ARPN"
  WEIGHT: "../hard_space/models/AFPN_rEAST_higher_IOU_X_101/model_0215000.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvARPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"

  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)
    FG_IOU_THRESHOLD: 0.6
    BG_IOU_THRESHOLD: 0.6

  RRPN:
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (2, 4, 8, 16, 32)
    GT_BOX_MARGIN: 1.4

  ARPN:
    BASE_SIZE: 640.
    NMS_THRESH: 0.8

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000)
  MAX_ITER: 280000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: '../hard_space/models/AFPN_rEAST_higher_IOU_X_101_IC15_ft/'
