INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512

MODEL:
  META_ARCHITECTURE: "ARPN"
  WEIGHT: "../hard_space/models/AFPN_rEAST_higher_IOU_X_101_IC15_ft/model_0235000.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 2000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvARPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"

  ROI_HEADS:
    NMS: 0.1
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 128
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)
    DETECTIONS_PER_IMG: 300
    NMS_TYPE: "remove"# "remove"

  RRPN:
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (2, 4, 8, 16, 32)
    GT_BOX_MARGIN: 1.4

  ARPN:
    BASE_SIZE: 640.
    SCALE_STACK: (0.25, 0.125, 0.0625, 0.03125, 0.015625)
    SIZE_STACK: (32, 64, 128, 256)
    NMS_TYPE: "remove"
    NMS_THRESH: 0.8
    SCORE_THRESH: 0.0

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000)
  MAX_ITER: 250000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 25000

TEST:
  DATASET_NAME: "IC15"
  CASCADE: False

DATALOADER:
  SIZE_DIVISIBILITY: 1

# OUTPUT_DIR: './models/ICDAR13_15_17_Trial_AFPN/'
