DATALOADER:
  SIZE_DIVISIBILITY: 1
DATASETS:
  TRAIN: ("RRPN_train_ft",)
INPUT:
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TRAIN: (640,)
  ROTATION_RANGE: (20, 10)
MODEL:
  ARPN:
    BASE_SIZE: 640.0
    CONV_STACK: 1
    NMS_THRESH: 0.8
    NMS_TYPE: remove
    SCALE_STACK: (0.25, 0.125, 0.0625, 0.03125, 0.015625)
    SCORE_THRESH: 0.0
    SIZE_STACK: (32, 64, 128, 256)
    USE_GN: false
  BACKBONE:
    CONV_BODY: R-50-FPN
    OUT_CHANNELS: 256
  META_ARCHITECTURE: ARPN
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: FPNPredictor
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.6
    DETECTIONS_PER_IMG: 300
    FG_IOU_THRESHOLD: 0.6
    NMS_TYPE: remove
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)
    USE_FPN: true
  RPN:
    FPN_POST_NMS_TOP_N_TEST: 600
    POST_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    RPN_HEAD: SingleConvARPNHead
    USE_FPN: true
  RRPN:
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (2, 4, 8, 16, 32)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    GT_BOX_MARGIN: 1.4
  WEIGHT: ../hard_space/models/AFPN_rEAST_Synth800K_pretrain_standard/model_0015000.pth
OUTPUT_DIR: ../hard_space/models/AFPN_rEAST_Synth800K_pretrain_standar_ft/
SOLVER:
  BASE_LR: 2.0e-05
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 1
  MAX_ITER: 240000
  STEPS: (100000, 200000)
  WEIGHT_DECAY: 0.0001
TEST:
  CASCADE: false
  DATASET_NAME: IC15
